force-app/main/default/objects/Account/fields/OfferName__c.field-meta.xml
<CustomField>
    <fullName>OfferName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Оферта</label>
    <referenceTo>Offer__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Offer__c/Offer__c.object-meta.xml
<CustomObject>
    <label>Оферта</label>
    <nameField>
        <displayFormat>АО-{0000}</displayFormat>
        <label>Offer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/triggers/OfferDeleteHandler.cls
/**
 * Created by OLga Skrynnikova on 20.09.2019.
 */

public with sharing class OfferDeleteHandler {

    public static void OfferToDeletemethod(List<Account> accs){
        List <Offer__c> offs = new List <Offer__c>();
        for (Account a : accs) {
            Offer__c offToDelete = [SELECT Id FROM Offer__c WHERE Id =: a.OfferName__c];
            offs.add(offToDelete);
        }
        try {
            delete offs;
            delete accs;
        } catch(Exception e) {
            System.debug('The following exception has occurred: ' + e.getMessage());
        }

    }
}